### PR TITLE
Fix #260 - SimpleType validation converts values

### LINKED ISSUE #260: SimpleType modifies value during validation
`SimpleType` is defined as `t.Int | t.Bool | t.String | t.Float` which is used to validate ListQuery and Filters, in particular. During this validation it converts int-like strings to int. Later the filters are created with respect to collection schema. The value gets checked again but it is not string anymore which results in an error.

So a quick example of this error: you have a string column and you are trying to use int-like value in a filter.

There's a related [trafaret issue](https://github.com/Deepwalker/trafaret_forked/issues/69). Usage of newly-introduced Raw-types is suggested.

### PR DESCRIPTION
**Pull request by thenx**
Haven't run all the tests (only util ones) so please, double-check.

### CODE REVIEW

**Comment by jettify** [comment]
Looks like new trafaret has broken API for MongId
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/home/travis/build/aio-libs/aiohttp_admin/aiohttp_admin/backends/mongo.py", line 37, in list
    query = create_filter(filters, self._schema)
  File "/home/travis/build/aio-libs/aiohttp_admin/aiohttp_admin/backends/mongo_utils.py", line 105, in create_filter
    value = _check_value(column_traf_map, field_name, value)
  File "/home/travis/build/aio-libs/aiohttp_admin/aiohttp_admin/backends/mongo_utils.py", line 73, in _check_value
    value = apply_trafaret(trafaret, value)
  File "/home/travis/build/aio-libs/aiohttp_admin/aiohttp_admin/backends/mongo_utils.py", line 58, in apply_trafaret
    validate = trafaret.converter
AttributeError: 'MongoId' object has no attribute 'converter'
```
It is no longer have `converter` attribute

**Comment by thenx** [comment]
I've reverted trafaret version back to 0.10.4 and it looks like it has raw types and does not have mongoId issues

**Comment by thenx** [comment]
BTW, i've just had a look at `mongo_utils.py` and my gut tells me that smth might be wrong. I'm now sure why it was chosen to assign `validate` different values but it seems that `MongoId` had to be converted with `trafaret.converter`, but in case of `[MongoId]` `trafaret.check_and_return` willl be applied to each `MongoId`
```
def apply_trafaret(trafaret, value):
    validate = trafaret.check_and_return

    if isinstance(trafaret, MongoId):
        validate = trafaret.converter

    if isinstance(value, list):
        value = [validate(v) for v in value]
    else:
        value = validate(value)
    return value
```
Anyway, it looks like the lines for `MongoId` are not necessary anymore (and that will allow to update trafaret to 0.11.3).

**Comment by jettify** [comment]
Lets remove those lines tests are green.

**Pull request merged**
