### PR TITLE
Fix #280

### LINKED ISSUE #280: mongo_utils.apply_trafaret does not work with lists
`mongo_utils.apply_trafaret(t.List(t.String), ['123'])` returns DataError

For some reason in the lists case list_trafaret is applied to elements of list

### PR DESCRIPTION
**Pull request by thenx**

### CODE REVIEW

**Comment by thenx** [comment]
This fixes `mongo_utils.apply_trafaret(t.List(t.String), ['123'])` case which may arise when you have a list field in mongo and try to find entities with a particular value in such list using `$in` operator.
For instance, you may have a `tag` field with a type List(String) or List(MongoId) with tag ids.

**Comment by thenx** [comment]
Guys,
could you merge it. I'm going to close my repo.

**Comment by jettify** [comment]
sorry for delay, will try to find time tonight

**Comment by jettify** [comment]
thanks!

**Pull request merged**
